language: c
script: make && make test
compiler: gcc

addons:
  ssh_known_hosts: delfiin.waalaskala.com

before_install:
- openssl aes-256-cbc -K $encrypted_5517357261d5_key -iv $encrypted_5517357261d5_iv -in deploy_rsa.enc -out deploy_rsa -d

before_deploy:
- openssl aes-256-cbc -K $encrypted_5517357261d5_key -iv $encrypted_5517357261d5_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/bin ragnar@delfiin.waalaskala.com:/home/ragnar/travis-test/xxx
  on:
    branch: master
