#!/bin/bash

SRC="$TRAVIS_BUILD_DIR/bin"
STAMP="$(date +'%Y%m%d-%H%M%S')"
DST="ragnar@delfiin.waalaskala.com:/home/ragnar/travis-test/$STAMP"

rsync \
	-r \
	--delete-after \
	--quiet \
	"$SRC" \
	"$DST"
